---
openapi: 3.0.1
info:
  title: API Iume Public
  version: v1
  description: Public endpoints
paths:
  "/v1/restaurants/sections/{section_id}/products":
    get:
      summary: All products of a section
      tags:
      - Products
      description: If you need to get the preview, use preview params to true and
        put the token
      security:
      - bearer: []
      parameters:
      - name: section_id
        in: path
        required: true
        schema:
          type: integer
      - name: preview
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: products array preview
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/product"
        '404':
          description: section not found
          content: {}
  "/v1/restaurants/sections/{section_id}/products/{id}":
    get:
      summary: Get product by section id and product id
      tags:
      - Products
      security:
      - bearer: []
      parameters:
      - name: section_id
        in: path
        required: true
        schema:
          type: integer
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: preview
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: product found prewiew
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/product"
        '404':
          description: product not found
          content: {}
  "/v1/restaurants/{id}":
    get:
      summary: Get restaurant
      tags:
      - Restaurants
      description: If you need to get the preview, use preview params to true and
        put the token
      security:
      - bearer: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: by_id
        in: query
        required: false
        schema:
          type: string
      - name: preview
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: restaurant with preview
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/restaurant"
                  included:
                    type: array
                    items:
                      "$ref": "#/components/schemas/section"
        '404':
          description: restaurant not found
          content: {}
components:
  schemas:
    product:
      type: object
      properties:
        id:
          type: string
          example: '1'
        type:
          type: string
          example: products
        attributes:
          type: object
          properties:
            price:
              type: string
              example: '10.0'
            name:
              type: string
              example: Pasta with Tomato and Basil
            description:
              type: string
              example: Culver’s Restaurant was founded by the Culver family in 1984,
                which eventually branched out to more than 300 franchised restaurants
                all over the US. Culver’s is well-known for its ButterBurger, which
                made the restaurant extremely famous. They also have other items which
                include salads, sandwiches, desserts, etc.
              nullable: true
            position:
              type: integer
              example: 0
              nullable: true
            image:
              type: object
              nullable: true
              properties:
                original:
                  type: string
                  example: https://loremflickr.com/300/300
                small:
                  type: string
                  example: https://loremflickr.com/300/300
          required:
          - price
          - name
    section:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          example: sections
        attributes:
          type: object
          properties:
            name:
              type: string
              example: Drinks
            position:
              type: integer
              example: 1
    restaurant:
      type: object
      properties:
        type:
          type: string
          example: restaurants
        id:
          type: string
        attributes:
          type: object
          properties:
            name:
              type: string
            slug:
              type: string
            active:
              type: boolean
          required:
          - name
          - slug
          - active
        relationships:
          type: object
          properties:
            sections:
              type: object
              properties:
                data:
                  type: array
                  items:
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                        example: sections
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
- url: https://imenu-dev.herokuapp.com
  variables:
    defaultHost:
      default: https://imenu-dev.herokuapp.com
