---
openapi: 3.0.1
info:
  title: API Iume Owner
  version: v1
  description: Owner endpoints
paths:
  "/v1/owners/emails":
    get:
      summary: show email
      tags:
      - Emails
      parameters:
      - name: email
        in: query
        schema:
          type: integer
      security:
      - bearer: []
      responses:
        '200':
          description: email found
          content: {}
        '404':
          description: email not found
          content: {}
        '422':
          description: when email is blank
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: array
                    items:
                      type: string
                      example: can't be blank
  "/v1/owners/feedbacks":
    post:
      summary: create feedback
      tags:
      - Feedbacks
      security:
      - bearer: []
      parameters: []
      responses:
        '201':
          description: created success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  type:
                    type: string
                    exemple: feedbacks
                  attributes:
                    type: object
                    properties:
                      screen:
                        type: screen
                        example: home
                      body:
                        type: string
        '422':
          description: created success
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: array
                    items:
                      type: string
                      example: can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                feedback:
                  type: object
                  properties:
                    screen:
                      type: string
                      example: Home
                    body:
                      type: string
                      example: Consequatur aut totam eveniet hic facere similique
                        ut cum omnis?
              required:
              - body
  "/v1/owners/restaurants":
    post:
      summary: Create
      tags:
      - Restaurants
      security:
      - bearer: []
      parameters: []
      responses:
        '201':
          description: create restaurant
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/restaurant"
        '422':
          description: create failt
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: array
                    items:
                      type: string
                      example: can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                restaurant:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Lynch-Predovic
                    active:
                      type: boolean
              required:
              - name
              - active
    get:
      summary: All restaurants
      tags:
      - Restaurants
      security:
      - bearer: []
      responses:
        '200':
          description: return array
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/restaurant"
  "/v1/owners/restaurants/{id}":
    put:
      summary: update restaurant
      tags:
      - Restaurants
      security:
      - bearer: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '202':
          description: update success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/restaurant"
        '422':
          description: create failt
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: array
                    items:
                      type: string
                      example: can't be blank
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                restaurant:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Terry LLC
                    active:
                      type: boolean
              required:
              - name
              - active
    get:
      summary: show restaurant
      tags:
      - Restaurants
      security:
      - bearer: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: found
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: array
                    items:
                      type: string
                      example: can't be blank
        '404':
          description: not found
          content: {}
  "/v1/owners/restaurants/availability_slug":
    put:
      summary: check slug availability
      tags:
      - Restaurants
      security:
      - bearer: []
      parameters: []
      responses:
        '202':
          description: availability
          content: {}
        '422':
          description: availability
          content:
            application/json:
              schema:
                type: object
                properties:
                  slug:
                    type: array
                    items:
                      type: string
                      example:
                      - has already been taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                restaurant:
                  type: object
                  properties:
                    slug:
                      type: string
                      example: sit-nobis
              required:
              - name
              - active
  "/v1/owners/sessions":
    post:
      summary: Login
      tags:
      - Sessions
      parameters: []
      responses:
        '201':
          description: login success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: xxxxx
                required:
                - token
        '422':
          description: login fail
          content:
            application/json:
              schema:
                type: object
                properties:
                  password:
                    type: array
                    items:
                      type: string
                      example: Password wrong
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: object
                  properties:
                    email:
                      type: string
                      example: lauran@romaguera-hahn.com
                    password:
                      type: string
                      example: '12345678'
              required:
              - email
              - password
  "/v1/owners/sessions/me":
    delete:
      summary: Destroy session
      tags:
      - Sessions
      security:
      - bearer: []
      responses:
        '204':
          description: login success
          content: {}
        '401':
          description: when owner is not logged in
          content: {}
  "/v1/owners":
    post:
      summary: Creates a owner
      tags:
      - Owners
      parameters: []
      responses:
        '201':
          description: owner created
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: xxxxx
                required:
                - token
        '422':
          description: owner created fail
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: array
                    items:
                      type: string
                      example: Email is invalid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                owner:
                  type: object
                  properties:
                    email:
                      type: string
                      example: edward@emard.io
                    password:
                      type: string
                      example: '12345678'
                    password_confirmation:
                      type: string
                      example: '12345678'
              required:
              - email
              - password
              - password_confirmation
  "/v1/owners/me":
    get:
      summary: Show me
      tags:
      - Owners
      security:
      - bearer: []
      responses:
        '200':
          description: get me
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/owner"
    put:
      summary: Update me
      tags:
      - Owners
      security:
      - bearer: []
      parameters: []
      responses:
        '202':
          description: get me
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/owner"
        '422':
          description: owner update fail
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: array
                    items:
                      type: string
                      example: Email is invalid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                owner:
                  type: object
                  properties:
                    email:
                      type: string
                      example: royal@schultz.net
                    password:
                      type: string
                      example: '12345678'
                    password_confirmation:
                      type: string
                      example: '12345678'
              required:
              - email
              - password
              - password_confirmation
    delete:
      summary: Delete me
      tags:
      - Owners
      security:
      - bearer: []
      responses:
        '204':
          description: destroy success
          content: {}
components:
  schemas:
    owner:
      type: object
      properties:
        id:
          type: string
          example: '1'
        type:
          type: string
          example: owners
        attributes:
          type: object
          properties:
            email:
              type: string
              example: melvin@mcdermott-bogan.name
            name:
              type: string
              nullable: true
            created_at:
              type: string
              example: '2020-08-17 18:31:38 -0300'
            updated_at:
              type: string
              example: '2020-08-17 18:31:38 -0300'
          required:
          - email
    restaurant:
      type: object
      properties:
        type:
          type: string
          example: restaurants
        id:
          type: string
        attributes:
          type: object
          properties:
            name:
              type: string
            slug:
              type: string
            active:
              type: boolean
          required:
          - name
          - slug
          - active
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
- url: https://imenu-dev.herokuapp.com
  variables:
    defaultHost:
      default: https://imenu-dev.herokuapp.com
