default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { '0.0.0.0' } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { '5432' } %>
  user: <%= ENV.fetch("POSTGRES_USER") { '' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { '' } %>

development:
  <<: *default
  database: you_menu_development

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: you_menu_test

production:
  url: <%= ENV['DATABASE_URL'] %>
